name: Dev-to-docker

on:
  workflow_dispatch:

env:
  IMAGE_NAME: watchyourlan
  TAGS: dev


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version tag from env file
        uses: c-py/action-dotenv-to-setenv@v2
        with:
          env-file: .version

      - name: Echo version
        run: echo ${{ env.VERSION }}

      - name: Build and Push Docker Image to docker.io
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          tags: ${{ env.TAGS }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}